export const cards = [
  {
    id: 0,
    player: 'Pascal Siakam',
    imageBack: '/img/Pascal.png',
    textFront: 'card 0',
  },
  {
    id: 1,
    player: 'Malachi Flynn',
    imageBack: '/img/Malachi.png',
    textFront: 'Malachi Flynn 30 point game',
  },
  {
    id: 2,
    player: 'Gary Trent Jr.',
    imageBack: '/img/Gary.png',
    textFront: 'Chris Boucher 4 blocks',
  },
  {
    id: 3,
    player: 'Jakob Poeltl',
    imageBack: '/img/Poeltl.png',
    textFront: 'card 3',
  },
  {
    id: 4,
    player: 'Scottie Barnes',
    imageBack: '/img/Scottie.png',
    textFront: 'card 4',
  },
  {
    id: 5,
    player: 'Dennis Schöder',
    imageBack: '/img/Dennis.png',
    textFront: 'card 5',
  },
  {
    id: 6,
    player: 'Precious Achiuwa',
    imageBack: '/img/Precious.png',
    textFront: 'card 6',
  },
  {
    id: 7,
    player: 'Chris Boucher',
    imageBack: '/img/Chris.png',
    textFront: 'card 7',
  },
  {
    id: 8,
    player: 'Gradey Dick',
    imageBack: '/img/Gradey.png',
    textFront: 'card 8',
  },
  {
    id: 9,
    player: 'Jalen McDaniels',
    imageBack: '/img/Jalen.png',
    textFront: 'card 9',
  },
  {
    id: 10,
    player: 'Javon Liberty-Freeman',
    imageBack: '/img/Javon.png',
    textFront: 'Darko ejected from game',
  },
  {
    id: 11,
    player: 'Christian Koloko',
    imageBack: '/img/Koloko.png',
    textFront: 'card 11',
  },
  {
    id: 12,
    player: 'The Raptor',
    imageBack: '/img/Raptor.png',
    textFront: 'FREE',
    img: '/img/Raptor.png',
  },
  {
    id: 13,
    player: 'Gary Trent Jr.',
    imageBack: '/img/Gary.png',
    textFront: 'Precious to Pascal for the dunk',
  },
  {
    id: 14,
    player: 'O.G. Anunoby',
    imageBack: '/img/OG.png',
    textFront: 'card 14',
  },
  {
    id: 15,
    player: 'Thaddeus Young',
    imageBack: '/img/Thad.png',
    textFront: 'card 15',
  },
  {
    id: 16,
    player: 'Otto Porter Jr.',
    imageBack: '/img/Otto.png',
    textFront: 'card 16',
  },
  {
    id: 17,
    player: 'Marquis Nowell',
    imageBack: '/img/Marquis.png',
    textFront: 'card 17',
  },
  {
    id: 18,
    player: 'Ron Harper Jr.',
    imageBack: '/img/Ron.png',
    textFront: 'card 18',
  },
  {
    id: 19,
    player: 'Garrett Temple',
    imageBack: '/img/Temple.png',
    textFront: 'card 19',
  },
  {
    id: 20,
    player: 'Pascal Siakam',
    imageBack: '/img/Pascal.png',
    textFront: 'card 20',
  },
  {
    id: 21,
    player: 'O.G. Anunoby',
    imageBack: '/img/OG.png',
    textFront: 'card 21',
  },
  {
    id: 22,
    player: 'Scottie Barnes',
    imageBack: '/img/Scottie.png',
    textFront: 'card 22',
  },
  {
    id: 23,
    player: 'Jakob Poeltl',
    imageBack: '/img/Poeltl.png',
    textFront: 'card 23',
  },
  {
    id: 24,
    player: 'Dennis Schröder',
    imageBack: '/img/Dennis.png',
    textFront: 'card 24',
  },
];
