export const cards = [
  {
    id: 0,
    player: 'Pascal Siakam',
    imageBack: '/img/Pascal.png',
    textFront: 'Pascal outscores KD in 1st half',
  },
  {
    id: 1,
    player: 'Malachi Flynn',
    imageBack: '/img/Malachi.png',
    textFront: 'Malachi Flynn 20 point game',
  },
  {
    id: 2,
    player: 'Gary Trent Jr.',
    imageBack: '/img/Gary.png',
    textFront: 'Gary hits 4 or more threes',
  },
  {
    id: 3,
    player: 'Jakob Poeltl',
    imageBack: '/img/Poeltl.png',
    textFront: 'Jakob perfect from FT line',
  },
  {
    id: 4,
    player: 'Scottie Barnes',
    imageBack: '/img/Scottie.png',
    textFront: 'Scottie has a 3 and dunk',
  },
  {
    id: 5,
    player: 'Dennis Schöder',
    imageBack: '/img/Dennis.png',
    textFront: 'Dennis to Boucher for alley-Oop',
  },
  {
    id: 6,
    player: 'Precious Achiuwa',
    imageBack: '/img/Precious.png',
    textFront: 'Precious with power slam',
  },
  {
    id: 7,
    player: 'Chris Boucher',
    imageBack: '/img/Chris.png',
    textFront: 'Chris over jumps on 3PT shooter',
  },
  {
    id: 8,
    player: 'Gradey Dick',
    imageBack: '/img/Gradey.png',
    textFront: 'Booker has single digit pts in 1st half',
  },
  {
    id: 9,
    player: 'Jalen McDaniels',
    imageBack: '/img/Jalen.png',
    textFront: 'KD gets shot blocked',
  },
  {
    id: 10,
    player: 'Javon Liberty-Freeman',
    imageBack: '/img/Javon.png',
    textFront: 'Darko ejected from game',
  },
  {
    id: 11,
    player: 'Christian Koloko',
    imageBack: '/img/Koloko.png',
    textFront: 'Raptors lead after 1st half',
  },
  {
    id: 12,
    player: 'The Raptor',
    imageBack: '/img/Raptor.png',
    textFront: 'FREE',
    img: '/img/Raptor.png',
  },
  {
    id: 13,
    player: 'Gary Trent Jr.',
    imageBack: '/img/Gary.png',
    textFront: 'Gary gets a steal',
  },
  {
    id: 14,
    player: 'O.G. Anunoby',
    imageBack: '/img/OG.png',
    textFront: 'OG hits a non-corner 3',
  },
  {
    id: 15,
    player: 'Thaddeus Young',
    imageBack: '/img/Thad.png',
    textFront: 'Thad plays',
  },
  {
    id: 16,
    player: 'Otto Porter Jr.',
    imageBack: '/img/Otto.png',
    textFront: 'Otto plays',
  },
  {
    id: 17,
    player: 'Marquis Nowell',
    imageBack: '/img/Marquis.png',
    textFront: 'Raptors lead after 1st quarter',
  },
  {
    id: 18,
    player: 'Ron Harper Jr.',
    imageBack: '/img/Ron.png',
    textFront: 'Suns hit 7 3PTs after 1st half',
  },
  {
    id: 19,
    player: 'Garrett Temple',
    imageBack: '/img/Temple.png',
    textFront: 'Garrett plays',
  },
  {
    id: 20,
    player: 'Pascal Siakam',
    imageBack: '/img/Pascal.png',
    textFront: 'Siakam spin move basket',
  },
  {
    id: 21,
    player: 'O.G. Anunoby',
    imageBack: '/img/OG.png',
    textFront: 'OG for the dunk',
  },
  {
    id: 22,
    player: 'Scottie Barnes',
    imageBack: '/img/Scottie.png',
    textFront: 'Scottie with a no look pass',
  },
  {
    id: 23,
    player: 'Jakob Poeltl',
    imageBack: '/img/Poeltl.png',
    textFront: 'Jakob gets a double-double',
  },
  {
    id: 24,
    player: 'Dennis Schröder',
    imageBack: '/img/Dennis.png',
    textFront: 'Dennis makes 5 free throws',
  },
];
